[package]
name = "redis_cluster_toolkit"
version = "0.1.0"
authors = ["trevorlink <lvpidadiao@gmail.com>"]
edition = "2018"

[dependencies]
serde_derive = "1.0.82"
serde = "1.0"
toml = "0.4"
rand = "0.6"
redis_cluster_rs = "0.1.5"