redis_addrs = ["hello", "world"]
pattern = "%s"

[util]
log_dir = "./log"
log_level = "info"

[server]
listen_port = 6700


[cluster]
cluster_addrs = [["192.168.110.162:6379"]]
cluster_passwords = [""]